[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "advent"
harness = false
